// <auto-generated />
using System;
using System.Collections.Generic;
using GreedyNose.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreedyNose.Api.Data.Migrations
{
    [DbContext(typeof(GreedyNoseDbContext))]
    [Migration("20260929143539_AddAccountSyncStateSessionHash")]
    partial class AddAccountSyncStateSessionHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreedyNose.Api.Data.AccountSyncState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSyncCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSessionIdHash")
                        .HasColumnType("text");

                    b.HasKey("UserId", "AccountKey");

                    b.ToTable("AccountSyncStates", (string)null);
                });

            modelBuilder.Entity("GreedyNose.Api.Data.Debit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AmountEUR")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasTime")
                        .HasColumnType("boolean");

                    b.Property<string>("PayeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "AccountKey");

                    b.HasIndex("UserId", "PayeeId");

                    b.ToTable("Debits", (string)null);
                });

            modelBuilder.Entity("GreedyNose.Api.Data.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens", (string)null);
                });

            modelBuilder.Entity("GreedyNose.Api.Data.NotificationLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DebitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DebitId")
                        .IsUnique();

                    b.ToTable("NotificationLog", (string)null);
                });

            modelBuilder.Entity("GreedyNose.Api.Data.Payee", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CreditorAgentsSeen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("IbansSeen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("NormalizedNamesSeen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("UserId", "Id");

                    b.ToTable("Payees", (string)null);
                });

            modelBuilder.Entity("GreedyNose.Api.Data.Rule", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayeeId")
                        .HasColumnType("text");

                    b.Property<decimal?>("AmountEUR")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PayeeId");

                    b.ToTable("Rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rules_AmountEUR_Positive", "\"AmountEUR\" IS NULL OR \"AmountEUR\" > 0");

                            t.HasCheckConstraint("CK_Rules_Classification", "\"Classification\" IN ('good', 'bad')");
                        });
                });

            modelBuilder.Entity("GreedyNose.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f0d7c3a-8b1e-4d6a-9a52-3c7e1b2f4a90"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GreedyNose.Api.Data.AccountSyncState", b =>
                {
                    b.HasOne("GreedyNose.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreedyNose.Api.Data.Debit", b =>
                {
                    b.HasOne("GreedyNose.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreedyNose.Api.Data.Payee", null)
                        .WithMany()
                        .HasForeignKey("UserId", "PayeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GreedyNose.Api.Data.DeviceToken", b =>
                {
                    b.HasOne("GreedyNose.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreedyNose.Api.Data.NotificationLogEntry", b =>
                {
                    b.HasOne("GreedyNose.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreedyNose.Api.Data.Debit", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DebitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GreedyNose.Api.Data.Payee", b =>
                {
                    b.HasOne("GreedyNose.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreedyNose.Api.Data.Rule", b =>
                {
                    b.HasOne("GreedyNose.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreedyNose.Api.Data.Payee", null)
                        .WithOne()
                        .HasForeignKey("GreedyNose.Api.Data.Rule", "UserId", "PayeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
